import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Share/Navbar";
import Footer from "@/components/Share/Footer";
import ContextProvider from "@/context/ContextProvider";
import SearchBar from "@/components/Share/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="container">
      <body className={inter.className}>

        <ContextProvider>
        <Navbar />
        <SearchBar  />
        {children}
        <Footer />
        </ContextProvider>
        </body>
    </html>
  );
}
